import time
import streamlit as st
from Llm import QAModel


st.set_page_config(page_icon="icon.png")
col1, col2 = st.columns([0.7, 2])
with col1:
    st.image("icon.png", width=150)
with col2:
    st.title("MediSearch")
    st.write(
        "An interactive chat to explore PubMed Articles about intelligence from 2013 to 2023"
    )
st.write("")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# if "model" not in st.session_state:
#     st.session_state.model = QAModel(model_id="meta-llama/Llama-2-13b-chat-hf")

# Display chat messages from history


def display_role_name(role):
    if role == "user":
        st.markdown("**You**")
    else:
        st.markdown("**MediSearch Bot**")


def display_chat_messages():
    for message in st.session_state.messages:
        role = message["role"]
        with st.chat_message(role):
            display_role_name(role)
            st.markdown(message["content"])


# def get_icon(role):
#     if role == 'user':
#         return "images/user.png"
#     else:
#         return "images/icon.png"


display_chat_messages()

# Sidebar with a button to delete chat history
with st.sidebar:
    # Use columns to center the button
    col1, col2, col3 = st.columns([0.5, 2, 0.5])
    with col2:  # This column will contain the button, making it centered
        if st.button("Delete Chat History"):
            st.session_state.messages = []
            st.rerun()

# create a typing effect


def stream_response():
    for word in response.split():
        yield word + " "
        time.sleep(0.02)


# def display_search_results(results):
#     if not results:
#         st.write(
#             "No relevant articles found. The response was solely generated by the knowledge of the Chatbot.")
#         return
#     else:
#         st.write(
#             "The answer was based on the articles below, which you might want to consider looking into.")

#     for num, doc in enumerate(results):
#         # TODO: Do we want the relevancy score to be displayed?
#         with st.expander(f"{doc.metadata['title']}"):
#             st.markdown(f"**PMID:** {doc.metadata['pmid_id']}")
#             st.markdown(f"**Authors:** {'; '.join(doc.metadata['authors'])}")
#             st.markdown(f"**Date:** {doc.metadata['date']}")
#             st.markdown(f"**Journal:** {doc.metadata['journal']}")
#             st.markdown(f"**Relevant Content:** {doc.page_content}")


prompt = st.chat_input("What do you want to know?")
if prompt:
    # Diplay user message
    with st.chat_message("user"):
        display_role_name("user")
        st.markdown(prompt)

    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})
    response = "test"
    # response = st.session_state.model.ask(prompt)
    # documents = response['docs']  # TODO: display the documents
    # response = response['answer'].replace('\nAssistant: ', '')

    with st.chat_message("ai"):
        display_role_name("ai")
        st.write_stream(stream_response)
        # display_search_results(documents)

    st.session_state.messages.append({"role": "ai", "content": response})
